[Vue] Rename AngularJSTests suite to ClientTests.
matomo-org/travis-scripts pull request #83
Opened 2022-10-16 16:31 UTC by diosmosis

As title.

Merge w/ https://github.com/matomo-org/matomo/pull/19502

2022-10-17 09:02 UTC, sgiehl commented
@diosmosis merging this one will break tests on 4.x-dev, right? Maybe we should keep the angularjs for bc here?

2022-10-17 12:03 UTC, diosmosis commented
we could check for both here

2022-10-26 09:06 UTC, sgiehl requested changes
Those should remain for BC reasons

2022-10-26 09:06 UTC, sgiehl commented on setup_mysql_tmpfs.sh
> +if [ "$SKIP_PIWIK_TEST_PREPARE" == "1" ] || [ "$TEST_SUITE" == "ClientTests" ] || [ "$TEST_SUITE" == "UnitTests" ] || [ "$TEST_SUITE" == "JavascriptTests" ]; then
```suggestion
if [ "$SKIP_PIWIK_TEST_PREPARE" == "1" ] || [ "$TEST_SUITE" == "AngularJSTests" ] || [ "$TEST_SUITE" == "ClientTests" ] || [ "$TEST_SUITE" == "UnitTests" ] || [ "$TEST_SUITE" == "JavascriptTests" ]; then
```

2022-10-26 09:06 UTC, sgiehl commented on setup_webserver.sh
> +if [ "$SKIP_PIWIK_TEST_PREPARE" == "1" ] || [ "$TEST_SUITE" == "ClientTests" ] || [ "$TEST_SUITE" == "UnitTests" ]; then
```suggestion
if [ "$SKIP_PIWIK_TEST_PREPARE" == "1" ] || [ "$TEST_SUITE" == "AngularJSTests" ] || [ "$TEST_SUITE" == "ClientTests" ] || [ "$TEST_SUITE" == "UnitTests" ]; then
```

2022-10-27 07:57 UTC, merged